### ISSUE TITLE
Location of files - Schema

### ISSUE THREAD

**Issue by datatalking** [ndemo-richard/ndemo-master#11]
I'm reviewing your website code and wanted to ask about the schema for storing the static files.

Does it seem that there are three or four different copies of some files in your structure?

Can we refactor the structure so it is loaded in one place and floods to the rest?

<img width="819" alt="Screen Shot 2021-06-11 at 4 59 22 PM" src="https://user-images.githubusercontent.com/11813209/121758553-99f95b00-cad6-11eb-9e0a-facac69da26c.png">

**Comment by ndemo-richard** [comment]
That happened when I was changing the settings file.we can refactor it

**Comment by datatalking** [comment]
When you say we, do you mean you, your team?

I could step in an help. What should the file location be?

Can you include me as a contributor for this repo?
