### ISSUE TITLE
Django Standard setup?

### ISSUE THREAD

**Issue by datatalking** [ndemo-richard/ndemo-master#8]
Hello ndemo-richard, I'm really liking the look of your demo page.

Is it set up with standard Django rules and commands?

**Comment by datatalking** [comment]
I've been trying for a few hours now to install this and I'm getting a rash of errors.

Can you explain if this was run as "works on my machine" or did you follow standard "python manage.py migrate" setup?

its not wanting to install and there is isn't even a README.md file so I'm not sure of your install process.

**Comment by datatalking** [comment]
Collecting psycopg2-binary
  Using cached psycopg2_binary-2.8.6-cp38-cp38-macosx_10_9_x86_64.macosx_10_9_intel.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.5 MB)
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.8.6
(venv) (base) Vanessas-iMac:ndemo-master vanessawilson$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    import django_heroku
ModuleNotFoundError: No module named 'django_heroku'
(venv) (base) Vanessas-iMac:ndemo-master vanessawilson$ python3 manage.py migrate
Traceback (most recent call last):
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/core/management/base.py", line 86, in wrapped
    saved_locale = translation.get_language()
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 254, in get_language
    return _trans.get_language()
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/utils/translation/__init__.py", line 57, in __getattr__
    if settings.USE_I18N:
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vanessawilson/sbox/test/ndemo-master/ndemo/settings/__init__.py", line 1, in <module>
    from .base import *
  File "/Users/vanessawilson/sbox/test/ndemo-master/ndemo/settings/base.py", line 1, in <module>
    from ndemo.settings.common import *
  File "/Users/vanessawilson/sbox/test/ndemo-master/ndemo/settings/common.py", line 17, in <module>
    import django_heroku
ModuleNotFoundError: No module named 'django_heroku'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    main()
  File "manage.py", line 19, in main
    execute_from_command_line(sys.argv)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/core/management/base.py", line 367, in run_from_argv
    connections.close_all()
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/db/utils.py", line 208, in close_all
    for alias in self:
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/utils/connection.py", line 73, in __iter__
    return iter(self.settings)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/utils/connection.py", line 45, in settings
    self._settings = self.configure_settings(self._settings)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/db/utils.py", line 144, in configure_settings
    databases = super().configure_settings(databases)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/utils/connection.py", line 50, in configure_settings
    settings = getattr(django_settings, self.settings_name)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/vanessawilson/sbox/test/ndemo-master/venv/lib/python3.8/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/vanessawilson/sbox/test/ndemo-master/ndemo/settings/__init__.py", line 1, in <module>
    from .base import *
  File "/Users/vanessawilson/sbox/test/ndemo-master/ndemo/settings/base.py", line 1, in <module>
    from ndemo.settings.common import *
  File "/Users/vanessawilson/sbox/test/ndemo-master/ndemo/settings/common.py", line 17, in <module>
    import django_heroku
ModuleNotFoundError: No module named 'django_heroku'
(venv) (base) Vanessas-iMac:ndemo-master vanessawilson$ pip install django_heroku
Collecting django_heroku
  Using cached django_heroku-0.3.1-py2.py3-none-any.whl (6.2 kB)
Requirement already satisfied: whitenoise in ./venv/lib/python3.8/site-packages (from django_heroku) (5.2.0)
Collecting psycopg2
  Using cached psycopg2-2.8.6.tar.gz (383 kB)
Requirement already satisfied: django in ./venv/lib/python3.8/site-packages (from django_heroku) (3.2.3)
Collecting dj-database-url>=0.5.0
  Using cached dj_database_url-0.5.0-py2.py3-none-any.whl (5.5 kB)
Requirement already satisfied: asgiref<4,>=3.3.2 in ./venv/lib/python3.8/site-packages (from django->django_heroku) (3.3.4)
Requirement already satisfied: sqlparse>=0.2.2 in ./venv/lib/python3.8/site-packages (from django->django_heroku) (0.4.1)
Requirement already satisfied: pytz in ./venv/lib/python3.8/site-packages (from django->django_heroku) (2021.1)
Using legacy 'setup.py install' for psycopg2, since package 'wheel' is not installed.
Installing collected packages: psycopg2, dj-database-url, django-heroku
    Running setup.py install for psycopg2 ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/vanessawilson/sbox/test/ndemo-master/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-install-dsmvgqea/psycopg2_1589b94c0160423b89d9feaed0981a39/setup.py'"'"'; __file__='"'"'/private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-install-dsmvgqea/psycopg2_1589b94c0160423b89d9feaed0981a39/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-record-4o6ly2pb/install-record.txt --single-version-externally-managed --compile --install-headers /Users/vanessawilson/sbox/test/ndemo-master/venv/include/site/python3.8/psycopg2
         cwd: /private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-install-dsmvgqea/psycopg2_1589b94c0160423b89d9feaed0981a39/
    Complete output (139 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14.6-x86_64-3.8
    creating build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/_json.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/extras.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/compat.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/errorcodes.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/tz.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/_range.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/_ipaddress.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/_lru_cache.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/__init__.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/extensions.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/errors.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/sql.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    copying lib/pool.py -> build/lib.macosx-10.14.6-x86_64-3.8/psycopg2
    running build_ext
    building 'psycopg2._psycopg' extension
    creating build/temp.macosx-10.14.6-x86_64-3.8
    creating build/temp.macosx-10.14.6-x86_64-3.8/psycopg
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -DPSYCOPG_VERSION=2.8.6 (dt dec pq3 ext lo64) -DPG_VERSION_NUM=130003 -DHAVE_LO64=1 -I/Users/vanessawilson/sbox/test/ndemo-master/venv/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -I. -I/usr/local/include -I/usr/local/include/postgresql/server -c psycopg/psycopgmodule.c -o build/temp.macosx-10.14.6-x86_64-3.8/psycopg/psycopgmodule.o
    In file included from psycopg/psycopgmodule.c:28:
    In file included from ./psycopg/psycopg.h:35:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:63:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
     ^
    In file included from psycopg/psycopgmodule.c:28:
    In file included from ./psycopg/psycopg.h:35:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:11:
    In file included from /Library/Developer/CommandLineTools/usr/lib/clang/12.0.0/include/limits.h:21:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/limits.h:64:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/limits.h:8:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from psycopg/psycopgmodule.c:28:
    In file included from ./psycopg/psycopg.h:35:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:33:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from psycopg/psycopgmodule.c:28:
    In file included from ./psycopg/psycopg.h:35:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:27:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_dev_t;         /* dev_t */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'
    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'; did you mean '__uint128_t'?
    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'; did you mean '__int128_t'?
    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
            ^
    note: '__int128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
            ^
    note: '__uint128_t' declared here
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
            ^
    note: '__uint128_t' declared here
    In file included from psycopg/psycopgmodule.c:28:
    In file included from ./psycopg/psycopg.h:35:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_wctype_t;
            ^
    note: '__uint128_t' declared here
    In file included from psycopg/psycopgmodule.c:28:
    In file included from ./psycopg/psycopg.h:35:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    
    It appears you are missing some prerequisite to build the package from source.
    
    You may install a binary package by installing 'psycopg2-binary' from PyPI.
    If you want to install psycopg2 from source, please install the packages
    required for the build and try again.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <https://www.psycopg.org/docs/install.html>).
    
    error: command 'clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/vanessawilson/sbox/test/ndemo-master/venv/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-install-dsmvgqea/psycopg2_1589b94c0160423b89d9feaed0981a39/setup.py'"'"'; __file__='"'"'/private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-install-dsmvgqea/psycopg2_1589b94c0160423b89d9feaed0981a39/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/m3/jsfh6v792_bg33tq9dyqyv200000gn/T/pip-record-4o6ly2pb/install-record.txt --single-version-externally-managed --compile --install-headers /Users/vanessawilson/sbox/test/ndemo-master/venv/include/site/python3.8/psycopg2 Check the logs for full command output.

**Comment by ndemo-richard** [comment]
I dont understand what you mean by  "as "works on my machine""
you should edit the common.py file in settings ,  comment out the last line `django_heroku.settings(locals())` and change the database engine to match what you are using.

i have added a readme file how to set it up.

**Comment by datatalking** [comment]
"works on my machine" is a phrase people use when someone else has an error but the original writer has no errors. This usually comes from the original poster forgot a dependency or they customized it to fit and didn't document it.

1. So I've pulled the code and I've usually used postgresql as the database, what should I change it to?

2. Pip required an update and once I did that. I had to change style==1.1.0
```
The user requested style==1.1.6
    update 0.0.1 depends on style==1.1.0
```
3.  Then I had to change idna==2.5
```
    The user requested idna==3.1
    requests 2.25.1 depends on idna<3 and >=2.5

**Comment by datatalking** [comment]
Ok, I also figured out other issues.

1. For MacOS there is a known bug with wheel issues and psycopg2 has been disconnected somehow from libq so https://github.com/psycopg/psycopg2/issues/1200 they found a patch in the user installing "psycopg2-binary==2.9.0.dev0" in requirements.txt

2. I can update your README.md file with the final piece to the puzzle "python manage.py runserver" and it runs!!!!.

Thank you for making such a beautiful website, a friend of mine is loving your work!!!

**Comment by ndemo-richard** [comment]
Thank you you can update the readme file..I used linux environment for development

**Comment by datatalking** [comment]
I'm new to being a contributor on GitHub and now realized I missed a few steps. Instead of forking your repo, then editing my version of that.
I cloned your repo, made edits, and now can't push it because I'm not you.
Is this where I need to rebase my local to my cloud repo or ?

I'm using PyCharm as my IDE

**Comment by datatalking** [comment]
Ok I figured out how to rebase my repo, now how do I push or give you access to mine so you can update yours?
